language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@^1.3.2
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
