sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@^1.3.2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
